# -*- coding: utf-8 -*-
"""Trabalho_Final_Pedro_Henrique_Pereira.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y1JSbFNCNBN2l8yoiXKD7ZFhLzgdNsXm
"""

import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""O objetivo do presente trabalho é anaisar a partir de algumas das principais variáveis macroeconômicas o período pós Plano Real, especificamente de 2002 até o começo da crise em 2015 e compreender como que as variáveis estão relacionadas com o desenvolvimento nacional nesse período.

Para isso foram escolhidas 4 bases cada uma representando uma variável importante, dentre as 4 temos a Inflação, Taxa de desemprego, exportações líquidas e a Taxa Selic para a presente análise.
"""

inflação=pd.read_csv('Inflação.csv',sep=';',error_bad_lines = False)
desemprego=pd.read_csv('Taxadedesemprego.csv',sep=';',error_bad_lines = False)
exp=pd.read_csv('exportações liquidas.csv',sep=';',error_bad_lines = False)

"""Organizando a base de dados sobre o desemprego para fazer o gráfico. Algumas informações não eram importantes para a análise e o nome de uma coluna não era conveniente. Então organizei da melhor forma que eu achei conveniente para fazer um gráfico para a taxa de desemprego."""

desemprego=desemprego.drop(columns=['Unnamed: 2'])

desemprego.rename(columns={'Unnamed: 0': 'Data'}, inplace = True)

desemprego=desemprego.drop(0)

data=[]
for i in range(2002,2016):
  j=0
  while j<12:
    data.append(i)
    j+=1
del(data[0])
del(data[1])

desemprego.insert(1,"data",data,True)

desemprego

desemprego.loc[22]

"""Aqui criei uma iteração para incluir na lista "taxa" os valores dos ultimos meses apenas para trabalharmos com o mês de dezembro. Apenas para simplificar no gráfico futuro colocando a taxa de desemprego do último mês como o representante do respectivo ano."""

taxa=[]
for i in range(1,167):
  if i==10 or i==1:
    taxa.append(desemprego.loc[i]['Taxa de desemprego'])
  if i in [22,34,46,58,70,82,94,106,118,130,142,154,166]:
    taxa.append(desemprego.loc[i]['Taxa de desemprego'])

desemprego=desemprego.drop(columns=['Data'])

"""Criei uma dataframe para separar os valores importantes para fazer o gráfico de forma mais limpa e visual."""

desemprego2=pd.DataFrame()
desemprego2['Data']=[2002.03,2002.12,2003.12,2004.12,2005.12,2006.12,2007.12,2008.12,2009.12,2010.12,2011.12,2012.12,2013.12,2014.12,2015.12]
desemprego2['Taxa de desemprego']=taxa

"""O gráfico de desemprego foi colocado ao final do arquivo para fazer comparações com outros gráficos importantes para a análise."""

desemprego2

"""Organizando a base de dados sobre a inflação para fazer o gráfico.

Para considerar apenas a até o ano de 2020, removi as linhas que indicavam o ano de 2021.
"""

inflação=inflação.drop(26)
inflação=inflação.drop(27)

"""O dataframe abaixo possui a taxa de inflação acumulada de cada ano, logo, podemos considerar apenas o último mês."""

inflação

"""A iteração abaixo foi apenas para facilitar no momento de fazer o gráfico que está ao final com os demais gráficos de outras variáveis."""

x2=[]
y2=[]
for i in range(26):
  x2.append(inflação.loc[i]['  Data'])
  y2.append(inflação.loc[i]['Taxa de inflação'])

"""Trabalhando com uma série histórica da Selic e organizando o DataFrame para fazer o gráfico.

Essa série possui muitos dados e pode-se concluir que para esta análise não será necessária boa parte das datas. Portanto, consideraremos apenas as últimas datas a termos de comparação com as demais variáveis.
"""

codigo = 1178
url = 'http://api.bcb.gov.br/dados/serie/bcdata.sgs.{}/dados?formato=json'.format(codigo)

selic = pd.read_json(url)
selic =  selic.rename(columns = {selic.columns[1]:'selic em %'})
selic

"""Nessa iteração coloquei uma lista "aux" para inserir as últimas datas que estavam presentes na base. Através dessa iteração foi possível testar quais as datas que existiam e quais não existiam, caso não existissem era substituida manualmente por uma data imediatamente anterior."""

aux=[] # apenas para verificar quais dados estão disponiveis
for i in range(8895):
  if selic.loc[i]['data'] in ['30/12/2020','30/12/2019','28/12/2018','29/12/2017','30/12/2016','30/12/2015','30/12/2014','30/12/2013','28/12/2012','30/12/2011','30/12/2010','30/12/2009','30/12/2008','28/12/2007','28/12/2006','30/12/2005','30/12/2004','30/12/2003','30/12/2002','28/12/2001','29/12/2000','30/12/1999','30/12/1998','30/12/1997','30/12/1996','29/12/1995']:
    aux.append(selic.loc[i]['data'])
aux

"""A partir das datas já separadas, a fins de simplificação para justamente fazer um gráfico coerente com os outros de forma comparativa, substituiu-se as datas pelo seu respectivo ano. """

Selic_final_do_ano=pd.DataFrame()
b=[]
for i in range(1995,2022):
  b.append(i)
c=[]
Selic_final_do_ano['Data']=b

for i in range(8895):
  if i==8894:
    c.append(selic.loc[i]['selic em %'])
  if selic.loc[i]['data'] in ['30/12/2020','30/12/2019','28/12/2018','29/12/2017','30/12/2016','30/12/2015','30/12/2014','30/12/2013','28/12/2012','30/12/2011','30/12/2010','30/12/2009','30/12/2008','28/12/2007','28/12/2006','30/12/2005','30/12/2004','30/12/2003','30/12/2002','28/12/2001','29/12/2000','30/12/1999','30/12/1998','30/12/1997','30/12/1996','29/12/1995']:
    c.append(selic.loc[i]['selic em %'])
Selic_final_do_ano['Selic']=c

Selic_final_do_ano

"""Trabalhando com a base de dados do IBGE, sobre o balanço comercial do país.

Por conta da dificuldade de se trabalhar com uma base que separava por trimistres, resolveu-se que seria melhor somar os quatro semestres e, posteriormente, analisar a balança comercial durante os anos. Através disso saberíamos se foi positiva ou negativa.
"""

exp

saldo=[] #diferença entre trimestres
saldoano=[]
anualexp=[] #soma dos 4 trimestres de exp
anualimp=[] #soma dos 4 trimestres de imp
a=0
for i in range(1,103):
  saldo.append(exp.loc[0][i]-exp.loc[1][i])
for i in range(1,103):
  a+=exp.loc[0][i]
  if i%4==0:
    anualexp.append(int(a))
    a=0
for i in range(1,103):
  a+=exp.loc[1][i]
  if i%4==0:
    anualimp.append(a)
    a=0
# diferença no ano
for i in range(25):
  saldoano.append(int(anualexp[i]-anualimp[i]))
del(saldoano[0]) # a diferença é gigantesca, atrapalha a análise

anos=[]
for i in range(1997,2021):
  anos.append(str(i))
anos2=[]
for i in range(1996,2021):
  anos2.append(str(i))

"""Conclusão:

Agora mostrando os gráficos, é possível fazer algumas análises sobre o Brasil pós Plano Real.
Como é de conhecimento geral, o Brasil viveu uma época hiperinflacionária e, a partir do conhecimento dos dados da época, era possível ver um caso em que a Curva de Phillips original se aplicava na situação macroeconômica. Entretanto, por falta de dados sobre a taxa de desemprego durante essa época, não foi possível analisar isso nesse presente trabalho. No entanto, posteriormente ao Plano Real, é possível perceber a relação entre taxa de desemprego e inflação, agora a partir da Curva de Phillips que considera a taxa de desemprego natural, que será melhor explicada posteriormente.

Além disso, com os gráficos pode-se concluir que o período de (2002-2014), foram ótimos para a economia brasileira, uma vez que a taxa de desemprego diminuiu constantemente, a inflação permaneceu controlada e a taxa básica de juros foi diminuindo gradualmente. Entretanto, a grande pergunta que deve ser feita é "por que o Brasil cresceu durante esse período e como as variáveis se comportaram?", o que posteriormente será respondido com o auxílio do gráfico da Balança Comercial.

Fazendo uma breve análise sobre o gráfico, pode-se perceber que após 2014 o Brasil teve um grande crescimento da taxa de desemprego. Nesse momento começava a crise no Brasil.
"""

x=['2002.03','2002.12','2003.12','2004.12','2005.12','2006.12','2007.12','2008.12','2009.12','2010.12','2011.12','2012.12','2013.12','2014.12','2015.12']
y=[12.9,10.5,10.9,9.6,8.4,8.4,7.4,6.8,6.8,5.3,4.7,4.6,4.3,4.3,6.9] #Tive que colocar manualmente pois não era possível transformar em float
plt.figure(figsize=(15, 8))
plt.ylabel('Taxa de desemprego')
plt.xlabel('Data')
plt.title('Gráfico da taxa de desemprego')
plt.bar(x,y)
plt.show()

"""Comparando-se o ano de 2015 da taxa de desemprego e da taxa de inflação, podemos perceber que ambas as variáveis aumentaram bastante, o que era esperado de acordo com a curva de Phillips."""

plt.figure(figsize=(15, 8))
plt.bar(x2,y2)
plt.ylabel('Taxa de inflação')
plt.xlabel('Data')
plt.title('Gráfico da taxa de inflação')
plt.show()

"""Durante o mesmo ano de 2015 vemos que a Taxa Selic também aumentou, o que de fato indica a relação dessas variáveis."""

plt.figure(figsize=(15, 8))
plt.bar(Selic_final_do_ano['Data'],Selic_final_do_ano['Selic'])
plt.ylabel('Taxa Selic')
plt.xlabel('Data')
plt.title('Gráfico da taxa Selic')

"""A partir do gráfico sobre as exportações, percebe-se um crescente aumento,  muito por conta da taxa de câmbio ter se depreciado ano a ano, o que infelizmente não consegui encontrar uma base durante esse período da taxa de câmbio. No entanto, analisando-se as exportações líquidas, pode-se interpretar que durante o período de 2002-2007 o Brasil acumulou reservas, o que explica a diminuição da inflação e da taxa de desemprego concomitantemente. 

"""

plt.figure(figsize=(15, 8))
plt.bar(anos2,anualexp)
plt.ylabel('uma unidade=1000')
plt.xlabel('Ano correspondente')
plt.title('Exportações')
plt.show()

"""A partir do gráfico abaixo, mostra-se o boom das commodities no começo de 2002 até 2007, isso gerou um aumento das reservas no Brasil. Após 2007 o Brasil voltou a possuir uma balança comercial negativa até a grande chegada da grande depreciação do Real frente ao Dólar em 2016.

Analisando-se a balança comercial e o comportamento das variáveis acima de 2008 até 2015, percebe-se que quando o Brasil deixou de possuir exportações líquidas positivas tivemos um enorme decrescimo das demais variáveis, o que provavelmente foi uma das causas para o aumento da inflação e da taxa de desemprego em 2015. 
"""

plt.figure(figsize=(15, 8))
plt.bar(anos,saldoano)
plt.ylabel('Saldo com cada unidade=1000')
plt.xlabel('Ano correspondente')
plt.title('Balança Comercial')
plt.show()

"""Portanto, conclui-se que o período pós Plano Real, especificamente o período Lula, conseguiu atrelar a diminuição do desemprego à diminuição da taxa de inflação por conta do boom das commodities como foi possível averiguar no gráfico da Balança Comercial. Além disso, esse processo da diminuição da inflação e do desemprego representam também uma forma da curva de Phillips em que a inflação esperada se torna cada vez mais próxima de 0 por causa da constância e a taxa de desemprego se aproxima da taxa de desemprego natueal, o que torna essa relação como se fosse diretamente proporcionais, o que de fato aconteceu com a análise dos gráficos de inflação e desemprego. 
Nesse sentido, é possível analisar também a grave situação da crise que abateu o Brasil em 2014 quando se olha a Balança Comercial, atingiu-se o maior diferencial negativo da Balança Comercial e um aumento do desemprego também. 
Ademais,a partir dos gráficos dessas variáveis é possível entender outros mecanismos econômicos como a grande diminuição da Taxa Selic em 2020 para sustentar a economia durante a Pandemia e, logo depois, um leve crescimento da inflação. 
"""